import { Command } from "commander";
import type { CliContext } from "../../core/output.js";
import { registerContacts } from "./contacts.js";
import { registerCompanies } from "./companies.js";
import { registerDeals } from "./deals.js";
import { registerProperties } from "./properties.js";
import { registerAssociations } from "./associations.js";
import { registerOwners } from "./owners.js";
import { registerPipelines } from "./pipelines.js";
import { registerImports } from "./imports.js";
import { registerTickets } from "./tickets.js";
import { registerCustomObjects } from "./custom-objects.js";
import { registerEngagements } from "./engagements.js";
import { registerSync } from "./sync.js";
import { registerDescribe } from "./describe.js";
import { registerQuotes } from "./quotes.js";
import { registerProducts } from "./products.js";
import { registerLineItems } from "./line-items.js";
import { registerGoals } from "./goals.js";
import { registerPayments } from "./payments.js";
import { registerInvoices } from "./invoices.js";
import { registerSubscriptions } from "./subscriptions.js";
import { registerCards } from "./cards.js";
import { registerLeads } from "./leads.js";
import { registerCarts } from "./carts.js";
import { registerOrders } from "./orders.js";
import { registerDiscounts } from "./discounts.js";
import { registerFees } from "./fees.js";
import { registerTaxes } from "./taxes.js";
import { registerCommunications } from "./communications.js";
import { registerUsersObject } from "./users.js";
import { registerDatedApi } from "./dated.js";

export function registerCrm(program: Command, getCtx: () => CliContext): void {
  const crm = program.command("crm").description("HubSpot CRM objects");
  registerContacts(crm, getCtx);
  registerCompanies(crm, getCtx);
  registerDeals(crm, getCtx);
  registerTickets(crm, getCtx);
  registerProperties(crm, getCtx);
  registerAssociations(crm, getCtx);
  registerOwners(crm, getCtx);
  registerPipelines(crm, getCtx);
  registerImports(crm, getCtx);
  registerCustomObjects(crm, getCtx);
  registerEngagements(crm, getCtx);
  registerSync(crm, getCtx);
  registerDescribe(crm, getCtx);
  registerQuotes(crm, getCtx);
  registerProducts(crm, getCtx);
  registerLineItems(crm, getCtx);
  registerGoals(crm, getCtx);
  registerPayments(crm, getCtx);
  registerInvoices(crm, getCtx);
  registerSubscriptions(crm, getCtx);
  registerCards(crm, getCtx);
  registerLeads(crm, getCtx);
  registerCarts(crm, getCtx);
  registerOrders(crm, getCtx);
  registerDiscounts(crm, getCtx);
  registerFees(crm, getCtx);
  registerTaxes(crm, getCtx);
  registerCommunications(crm, getCtx);
  registerUsersObject(crm, getCtx);
  registerDatedApi(crm, getCtx);
}
