import { CliError, redactSensitive } from "./output.js";
import { getTelemetryContext } from "./telemetry-context.js";
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { randomUUID } from "node:crypto";

/**
 * Read the active trace session file (written by `hscli trace start`).
 * Returns the full session (file path + scope + includeBodies) if a
 * session is active, or undefined. Keeps session awareness decoupled
 * from the CLI command layer: the http client reads the state file on
 * construction, so ANY code path that opens a HubSpotClient
 * automatically participates in the trace.
 */
interface ActiveTraceSession {
  file: string;
  scope: "read" | "write" | "all";
  includeBodies: boolean;
}
function readActiveTraceSession(): ActiveTraceSession | undefined {
  const home = process.env.HSCLI_HOME?.trim() || join(homedir(), ".revfleet");
  const sessionPath = join(home, "trace-session.json");
  if (!existsSync(sessionPath)) return undefined;
  try {
    const session = JSON.parse(readFileSync(sessionPath, "utf8")) as {
      file?: string;
      scope?: string;
      includeBodies?: boolean;
    };
    if (!session.file) return undefined;
    const scope = session.scope === "read" || session.scope === "write" ? session.scope : "all";
    return { file: session.file, scope, includeBodies: Boolean(session.includeBodies) };
  } catch {
    return undefined;
  }
}
import { mapEndpointAvailabilityError, preflightEndpointCapability, recordEndpointSuccess } from "./capabilities.js";
import { getToken, getApiBaseUrl } from "./auth.js";
import { enforcePermissionProfile } from "./permissions.js";

/**
 * Paths where HubSpot embeds a raw token in the URL (notably
 * `/oauth/v1/access-tokens/{token}`). We replace the trailing segment
 * so trace/audit JSONL never captures the token verbatim.
 */
const TOKEN_IN_PATH_PREFIXES = [
  "/oauth/v1/access-tokens/",
  "/oauth/v1/refresh-tokens/",
];
function redactTokenPath(path: string): string {
  for (const prefix of TOKEN_IN_PATH_PREFIXES) {
    if (path.startsWith(prefix)) {
      const after = path.slice(prefix.length);
      const next = after.indexOf("/");
      const rest = next >= 0 ? after.slice(next) : "";
      return `${prefix}[REDACTED]${rest}`;
    }
  }
  return path;
}

/**
 * Create a HubSpotClient that is hublet-aware.
 * Automatically resolves the API base URL from the profile's hublet setting.
 */
export function createClient(profile: string, options: Omit<HubSpotClientOptions, "apiBaseUrl"> = {}): HubSpotClient {
  const token = getToken(profile);
  const apiBaseUrl = process.env.HSCLI_API_BASE_URL?.trim() || getApiBaseUrl(profile);
  return new HubSpotClient(token, { ...options, apiBaseUrl, profile });
}

export function createBrowserSessionClient(
  profile: string,
  options: Omit<HubSpotClientOptions, "auth" | "skipCapabilityPreflight"> & {
    cookie: string;
    csrfToken: string;
  },
): HubSpotClient {
  return new HubSpotClient("", {
    ...options,
    profile,
    auth: {
      kind: "browser-session",
      cookie: options.cookie,
      csrfToken: options.csrfToken,
    },
    skipCapabilityPreflight: true,
  });
}

export interface RequestOptions {
  method?: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  body?: unknown;
  idempotencyKey?: string;
  /**
   * Override the default `Content-Type: application/json`. Used when
   * HubSpot endpoints expect `text/plain`, `text/html`, or
   * `multipart/form-data` — e.g. `/cms/v3/source-code/*` template
   * uploads. When set, `rawBody` is sent verbatim instead of
   * JSON-stringifying `body`.
   */
  contentType?: string;
  /** Raw body string used when `contentType` is non-JSON. */
  rawBody?: string;
  /**
   * Multipart form data. When set, the request is sent as
   * `multipart/form-data` with a boundary generated by the runtime —
   * explicit `contentType` is ignored. Each entry is either:
   *   - `string`: added as a text field.
   *   - `{ path, filename?, contentType? }`: file field; the local
   *     file at `path` is read and attached as a binary part.
   *
   * HubSpot endpoints that require multipart bodies (and fail with
   * 415 on JSON or plain-text bodies) include:
   *   - `PUT /cms/v3/source-code/{env}/content/{path}` — template
   *     source uploads
   *   - `POST /cms/v3/hubdb/tables/{id}/draft/import` — CSV row
   *     import, parts: `config` (JSON string) + `file` (binary)
   *   - `POST /content/filemapper/v1/upload/{dest}` — the legacy
   *     endpoint `hs upload` uses
   *   - `POST /file-transport/v1/hubfiles/object-schemas` — HubFiles
   *     custom-object schemas
   *   - `POST /project-components-external/v3/upload/new-api` —
   *     project zip + IR (3 parts)
   */
  multipart?: Record<string, MultipartPart>;
}

export type MultipartPart =
  | string
  | { path: string; filename?: string; contentType?: string };

interface HubSpotClientOptions {
  requestId?: string;
  telemetryFile?: string;
  profile?: string;
  strictCapabilities?: boolean;
  /** Override the API base URL (e.g. "https://api-eu1.hubapi.com" for EU1 portals). */
  apiBaseUrl?: string;
  auth?: {
    kind: "browser-session";
    cookie: string;
    csrfToken: string;
  };
  skipCapabilityPreflight?: boolean;
}

const REQUEST_TIMEOUT_MS = 30_000;
const MAX_RETRIES = 3;
const MAX_BACKOFF_MS = 10_000;
const ROLLING_SAFETY_BUFFER = 1;
const DAILY_MIN_REMAINING_BUFFER = 5;
const DAILY_LOW_WATERMARK_RATIO = 0.02;
const ALLOWED_PATH_SCOPES = [
  "crm",
  "oauth",
  "marketing",
  "files",
  "forms",
  "cms",
  "automation",
  "conversations",
  "settings",
  "events",
  "communication-preferences",
  "webhooks",
  "account-info",
  "api",
  "integrations",
  "analytics",
  "email",
  "media-bridge",
  "feature",
  "broadcast",
  "broadcasts",
  "channels",
  "companies",
  "contacts",
  "content",
  "deals",
  "engagements",
  "extensions",
  "form",
  "owners",
  "reports",
  "submissions",
  "marketing-emails",
  "communication",
  "visitor-identification",
  "integrators",
  "calling",
  "properties",
  "tax",
  "scheduler",
  "appinstalls",
  "payments",
  "business-units",
  "form-integrations",
  "comments",
  // Survey + feedback endpoints (e.g. /feedback/v3/submissions)
  "feedback",
  // Legacy goals API (/goals/v1/*) — modern alternative is /crm/v3/objects/goal_targets
  "goals",
  // CMS content folder tree listing (used by design-manager tooling)
  "content-folders",
  // App dev + portal install analytics (undocumented —
  // /apps-dev/external/public/v3/{appId}/test-portal-installs,
  // /full/portal, /install-counts-without-test-portals)
  "apps-dev",
  // Hublets static-token app install (undocumented)
  "apps-hublets",
  // Developer file system — projects upload, deploy, logs, migrations
  // (used by `hs project upload` under the hood)
  "dfs",
  // New v3 project upload-with-IR endpoint (replaces dfs/v1 for apps)
  "project-components-external",
  // HubFiles custom-object schemas (used by `hs hubfiles`)
  "file-transport",
  // Local-dev-auth link flow (account linking)
  "localdevauth",
];

interface RollingQuotaState {
  max: number;
  remaining: number;
  intervalMs: number;
  resetAtMs: number;
}

interface DailyQuotaState {
  max: number;
  remaining: number;
  resetAtMs: number;
}

interface RateLimitSnapshot {
  secondly?: RollingQuotaState;
  rolling?: RollingQuotaState;
  daily?: DailyQuotaState;
  nextRequestAtMs: number;
}

const SHARED_RATE_LIMITS = new Map<string, RateLimitSnapshot>();

function sharedRateLimitState(key: string): RateLimitSnapshot {
  const existing = SHARED_RATE_LIMITS.get(key);
  if (existing) return existing;
  const created: RateLimitSnapshot = { nextRequestAtMs: 0 };
  SHARED_RATE_LIMITS.set(key, created);
  return created;
}

export class HubSpotClient {
  private readonly baseUrl: URL;
  private readonly requestId: string;
  private readonly telemetryFile?: string;
  private readonly traceScope: "read" | "write" | "all";
  private readonly traceIncludeBodies: boolean;
  private readonly profile: string;
  private readonly strictCapabilities: boolean;
  private readonly auth?: HubSpotClientOptions["auth"];
  private readonly skipCapabilityPreflight: boolean;
  private readonly rateLimitState: RateLimitSnapshot;
  // Portal timezone (e.g. "US/Eastern"). Fetched lazily from
  // /account-info/v3/details the first time daily quota headers appear,
  // then used so the daily reset calculation matches HubSpot's actual
  // reset time (HubSpot resets daily usage at midnight in the portal's
  // own timezone, not UTC). Falls back to "UTC" if detection fails.
  private portalTimeZone: string | undefined;
  private portalTimeZoneFetching: Promise<void> | undefined;

  constructor(private readonly token: string, options: HubSpotClientOptions = {}) {
    this.baseUrl = new URL(options.apiBaseUrl?.trim() || "https://api.hubapi.com");
    this.requestId = options.requestId?.trim() || process.env.HSCLI_REQUEST_ID?.trim() || randomUUID();
    // Telemetry priority:
    //   1. explicit --telemetry-file flag / options.telemetryFile
    //   2. HSCLI_TELEMETRY_FILE env var
    //   3. active trace session file (set by `hscli trace start`)
    // Users never need to re-pass --telemetry-file after `trace start`.
    const activeSession = readActiveTraceSession();
    this.telemetryFile = options.telemetryFile?.trim()
      || process.env.HSCLI_TELEMETRY_FILE?.trim()
      || activeSession?.file
      || undefined;
    // Only honor session scope/bodies when the telemetry file actually
    // comes from the active session. If the caller passed an explicit
    // --telemetry-file, they own the filtering policy.
    const telemetryFromSession = !options.telemetryFile?.trim()
      && !process.env.HSCLI_TELEMETRY_FILE?.trim()
      && activeSession?.file !== undefined;
    this.traceScope = telemetryFromSession ? (activeSession?.scope ?? "all") : "all";
    this.traceIncludeBodies = telemetryFromSession
      ? Boolean(activeSession?.includeBodies)
      : isEnvTrue(process.env.HSCLI_TRACE_BODIES);
    this.profile = options.profile?.trim() || process.env.HSCLI_PROFILE?.trim() || "default";
    this.strictCapabilities = options.strictCapabilities ?? isEnvTrue(process.env.HSCLI_STRICT_CAPABILITIES);
    this.auth = options.auth;
    this.skipCapabilityPreflight = Boolean(options.skipCapabilityPreflight);
    const authKind = this.auth?.kind ?? "bearer";
    this.rateLimitState = sharedRateLimitState(`${this.profile}|${this.baseUrl.origin}|${authKind}`);
  }

  async request(path: string, options: RequestOptions = {}, attempt = 0): Promise<unknown> {
    const method = options.method ?? "GET";
    enforcePermissionProfile(this.profile, method);
    const url = this.resolveUrl(path);
    const pathname = new URL(url).pathname;
    const idempotencyKey = resolveIdempotencyKey(method, options.idempotencyKey);
    const startedAt = Date.now();

    await this.beforeRateLimitedRequest(pathname);
    if (!this.skipCapabilityPreflight) {
      preflightEndpointCapability({
        profile: this.profile,
        path: pathname,
        strict: this.strictCapabilities,
      });
    }

    try {
      // Multipart takes precedence. When set, we build a FormData
      // instance and hand it to fetch — Node 20+ emits the correct
      // `multipart/form-data; boundary=…` Content-Type automatically.
      // We MUST omit the Content-Type header ourselves; hardcoding
      // `multipart/form-data` without a boundary is the #1 cause of
      // HubSpot's 415 "Unsupported Media Type" responses.
      let bodyToSend: string | FormData | undefined;
      const headers: Record<string, string> = {
        "X-Hubcli-Request-Id": this.requestId,
        ...(idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {}),
      };
      if (this.auth?.kind === "browser-session") {
        headers.Cookie = this.auth.cookie;
        headers["x-hubspot-csrf-hubspotapi"] = this.auth.csrfToken;
        headers.Accept = "application/json";
      } else {
        headers.Authorization = `Bearer ${this.token}`;
      }
      if (options.multipart) {
        const { readFile } = await import("node:fs/promises");
        const { basename } = await import("node:path");
        const form = new FormData();
        for (const [field, part] of Object.entries(options.multipart)) {
          if (typeof part === "string") {
            form.append(field, part);
          } else {
            const bytes = await readFile(part.path);
            const filename = part.filename ?? basename(part.path);
            const type = part.contentType ?? "application/octet-stream";
            // Node 20+ Blob accepts Uint8Array; fetch auto-sets
            // Content-Type + boundary when body is FormData.
            form.append(field, new Blob([bytes], { type }), filename);
          }
        }
        bodyToSend = form;
      } else {
        const contentType = options.contentType ?? "application/json";
        headers["Content-Type"] = contentType;
        bodyToSend =
          options.rawBody !== undefined
            ? options.rawBody
            : options.body !== undefined
              ? JSON.stringify(options.body)
              : undefined;
      }
      const response = await fetch(url, {
        method,
        headers,
        body: bodyToSend,
        signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      });

      this.observeRateLimitHeaders(response.headers);

      if (response.status === 429 || response.status >= 500) {
        if (response.status === 429) {
          this.observeTooManyRequests(response.headers);
          const details = await safeJson(response);
          if (this.isDailyQuotaExhausted() || isDailyRateLimit(details)) {
            throw this.dailyQuotaError(details);
          }
        }
        if (attempt >= MAX_RETRIES) {
          throw new CliError("HTTP_RETRY_EXHAUSTED", `Request failed after ${MAX_RETRIES + 1} attempts`, response.status);
        }
        const retryAfterMs = parseRetryAfterMs(response.headers.get("retry-after"));
        const backoff = retryAfterMs ?? Math.min(1000 * 2 ** attempt, MAX_BACKOFF_MS);
        await new Promise((r) => setTimeout(r, backoff));
        return this.request(path, { ...options, idempotencyKey }, attempt + 1);
      }

      if (!response.ok) {
        const details = await safeJson(response);
        this.emitTelemetry({
          method,
          path: pathname,
          status: response.status,
          durationMs: Date.now() - startedAt,
          attempt,
          ...(this.traceIncludeBodies ? { requestBody: options.body, responseBody: details } : {}),
        });
        const endpointError = this.skipCapabilityPreflight ? undefined : mapEndpointAvailabilityError({
          profile: this.profile,
          path: pathname,
          statusCode: response.status,
          details,
        });
        if (endpointError) throw endpointError;
        throw new CliError("HTTP_ERROR", `HubSpot API request failed (${response.status})`, response.status, details);
      }

      if (!this.skipCapabilityPreflight) {
        recordEndpointSuccess({ profile: this.profile, path: pathname, statusCode: response.status });
      }
      if (response.status === 204) {
        this.emitTelemetry({
          method,
          path: pathname,
          status: response.status,
          durationMs: Date.now() - startedAt,
          attempt,
          ...(this.traceIncludeBodies ? { requestBody: options.body } : {}),
        });
        return { ok: true };
      }
      const responseBody = await safeJson(response);
      this.emitTelemetry({
        method,
        path: pathname,
        status: response.status,
        durationMs: Date.now() - startedAt,
        attempt,
        ...(this.traceIncludeBodies ? { requestBody: options.body, responseBody } : {}),
      });
      return responseBody;
    } catch (error) {
      this.emitTelemetry({
        method,
        path: pathname,
        durationMs: Date.now() - startedAt,
        attempt,
        error: error instanceof Error ? error.message : String(error),
      });
      if (error instanceof CliError) throw error;
      if (error instanceof DOMException && error.name === "TimeoutError") {
        throw new CliError("HTTP_TIMEOUT", `Request timed out after ${REQUEST_TIMEOUT_MS}ms`);
      }
      if (attempt >= MAX_RETRIES) {
        throw new CliError("NETWORK_ERROR", "Network request failed", undefined, { cause: String(error) });
      }
      await new Promise((r) => setTimeout(r, 1000 * 2 ** attempt));
      return this.request(path, { ...options, idempotencyKey }, attempt + 1);
    }
  }

  private resolveUrl(path: string): string {
    if (!path.startsWith("/")) {
      throw new CliError("INVALID_PATH", "Request path must start with '/'");
    }

    const url = new URL(path, this.baseUrl);
    if (url.origin !== this.baseUrl.origin) {
      throw new CliError("INVALID_PATH", "Request URL origin is not allowed");
    }

    if (!ALLOWED_PATH_SCOPES.some((scope) => url.pathname === `/${scope}` || url.pathname.startsWith(`/${scope}/`))) {
      throw new CliError("INVALID_PATH_SCOPE", "Request path escapes allowed HubSpot API scope");
    }

    return url.toString();
  }

  private emitTelemetry(event: {
    method: string;
    path: string;
    status?: number;
    durationMs: number;
    attempt: number;
    error?: string;
    requestBody?: unknown;
    responseBody?: unknown;
    requestBytes?: number;
    responseBytes?: number;
  }): void {
    if (!this.telemetryFile) return;
    // Scope filter — set by `hscli trace start --scope read|write|all`.
    // THROTTLE pseudo-events are always emitted (diagnostic signal, not
    // a real request, so scope doesn't apply).
    if (this.traceScope !== "all" && event.method !== "THROTTLE") {
      const isWrite = event.method === "POST" || event.method === "PUT"
        || event.method === "PATCH" || event.method === "DELETE";
      if (this.traceScope === "read" && isWrite) return;
      if (this.traceScope === "write" && !isWrite) return;
    }
    try {
      // Redact path (e.g. /oauth/v1/access-tokens/<TOKEN>) and bodies
      // before persisting to disk. The trace help text advertises
      // "redacted for secrets" — this is where that guarantee is kept.
      const safePath = redactTokenPath(event.path);
      const safeEvent = {
        ...event,
        path: safePath,
        ...(event.requestBody !== undefined ? { requestBody: redactSensitive(event.requestBody) } : {}),
        ...(event.responseBody !== undefined ? { responseBody: redactSensitive(event.responseBody) } : {}),
        ...(event.error ? { error: redactSensitive(event.error) } : {}),
      };
      // Baseline event: always includes ts + requestId + profile.
      // toolName comes from AsyncLocalStorage (set by the MCP handler
      // wrapper) so concurrent MCP calls don't race on a process-global.
      const tcx = getTelemetryContext();
      // changeTicket: ALS wins for MCP (race-safe), env fallback for CLI
      // (single-invocation per process, preAction sets HSCLI_CHANGE_TICKET).
      const changeTicket = tcx?.changeTicket
        || process.env.HSCLI_CHANGE_TICKET?.trim()
        || undefined;
      appendFileSync(this.telemetryFile, JSON.stringify({
        ts: new Date().toISOString(),
        requestId: this.requestId,
        profile: this.profile,
        toolName: tcx?.toolName,
        changeTicket,
        ...safeEvent,
      }) + "\n", "utf8");
    } catch {
      // Telemetry must not break CLI execution.
    }
  }

  private async beforeRateLimitedRequest(path: string): Promise<void> {
    let waitMs = this.computeWaitMs();
    while (waitMs > 0) {
      await new Promise((resolve) => setTimeout(resolve, waitMs));
      this.emitTelemetry({
        method: "THROTTLE",
        path,
        durationMs: waitMs,
        attempt: 0,
      });
      waitMs = this.computeWaitMs();
    }
    const now = Date.now();
    if (this.isDailyQuotaExhausted(now)) {
      throw this.dailyQuotaError();
    }
    this.reserveBudget();
  }

  private computeWaitMs(): number {
    const now = Date.now();
    let waitMs = 0;

    waitMs = Math.max(waitMs, this.computeWindowWaitMs(this.rateLimitState.secondly, now));
    waitMs = Math.max(waitMs, this.computeWindowWaitMs(this.rateLimitState.rolling, now));

    const nextRequestAt = this.rateLimitState.nextRequestAtMs;
    if (nextRequestAt > now) {
      waitMs = Math.max(waitMs, nextRequestAt - now);
    }

    return waitMs;
  }

  private computeWindowWaitMs(window: RollingQuotaState | undefined, now: number): number {
    if (!window) return 0;
    if (now >= window.resetAtMs) {
      window.remaining = window.max;
      window.resetAtMs = now + window.intervalMs;
      return 0;
    }
    if (window.remaining <= ROLLING_SAFETY_BUFFER) {
      return window.resetAtMs - now + 25;
    }
    return 0;
  }

  private reserveBudget(): void {
    const now = Date.now();
    this.reserveWindowBudget(this.rateLimitState.secondly, now);
    this.reserveWindowBudget(this.rateLimitState.rolling, now);
    const daily = this.rateLimitState.daily;
    if (daily && now < daily.resetAtMs && daily.remaining > 0) {
      daily.remaining -= 1;
    }
  }

  private reserveWindowBudget(window: RollingQuotaState | undefined, now: number): void {
    if (window && now < window.resetAtMs && window.remaining > 0) {
      window.remaining -= 1;
    }
  }

  private observeRateLimitHeaders(headers: Headers): void {
    const now = Date.now();

    const secondlyMax = parsePositiveInt(headers.get("x-hubspot-ratelimit-secondly"));
    const secondlyRemaining = parseNonNegativeInt(headers.get("x-hubspot-ratelimit-secondly-remaining"));
    if (secondlyMax !== undefined && secondlyRemaining !== undefined) {
      this.rateLimitState.secondly = {
        intervalMs: 1000,
        max: secondlyMax,
        remaining: secondlyRemaining,
        resetAtMs: now + 1000,
      };
    }

    const intervalMs = parsePositiveInt(headers.get("x-hubspot-ratelimit-interval-milliseconds"));
    const max = parsePositiveInt(headers.get("x-hubspot-ratelimit-max"));
    const remaining = parseNonNegativeInt(headers.get("x-hubspot-ratelimit-remaining"));
    if (intervalMs !== undefined && max !== undefined && remaining !== undefined) {
      this.rateLimitState.rolling = {
        intervalMs,
        max,
        remaining,
        resetAtMs: now + intervalMs,
      };
    }

    const dailyMax = parsePositiveInt(headers.get("x-hubspot-ratelimit-daily"));
    const dailyRemaining = parseNonNegativeInt(headers.get("x-hubspot-ratelimit-daily-remaining"));
    if (dailyMax !== undefined && dailyRemaining !== undefined) {
      const resetAtMs = nextMidnightMs(now, this.portalTimeZone ?? "UTC");
      this.rateLimitState.daily = {
        max: dailyMax,
        remaining: dailyRemaining,
        resetAtMs,
      };
      this.rateLimitState.nextRequestAtMs = this.computeDailyPacingNextAt(resetAtMs, dailyMax, dailyRemaining);
      // Lazily fetch the portal's timezone on first daily-quota sighting so
      // subsequent resets use the correct local midnight.
      this.ensurePortalTimeZoneFetched();
    }
  }

  /**
   * Fetch the portal's timezone once and cache it on the client instance.
   * /account-info/v3/details returns a `timeZone` string (e.g. "US/Eastern").
   * If the request fails or times out, fall back to "UTC" silently — daily
   * quota tracking still works, just off by a few hours for non-UTC portals.
   */
  private ensurePortalTimeZoneFetched(): void {
    if (this.auth?.kind === "browser-session") {
      this.portalTimeZone = "UTC";
      return;
    }
    if (this.portalTimeZone || this.portalTimeZoneFetching) return;
    const url = this.resolveUrl("/account-info/v3/details");
    this.portalTimeZoneFetching = (async () => {
      try {
        const response = await fetch(url, {
          method: "GET",
          headers: {
            Authorization: `Bearer ${this.token}`,
            "X-Hubcli-Request-Id": this.requestId,
          },
          signal: AbortSignal.timeout(5_000),
        });
        if (response.ok) {
          const body = await response.json().catch(() => null) as { timeZone?: string } | null;
          if (body?.timeZone && typeof body.timeZone === "string") {
            this.portalTimeZone = body.timeZone;
            return;
          }
        }
      } catch {
        // silent fallback
      }
      this.portalTimeZone = "UTC";
    })();
  }

  private observeTooManyRequests(headers: Headers): void {
    const now = Date.now();
    const retryAfterMs = parseRetryAfterMs(headers.get("retry-after"));
    const retryAtMs = now + (retryAfterMs ?? 1000);

    this.rateLimitState.nextRequestAtMs = Math.max(this.rateLimitState.nextRequestAtMs, retryAtMs);
    if (this.rateLimitState.secondly) {
      this.rateLimitState.secondly.remaining = 0;
      this.rateLimitState.secondly.resetAtMs = Math.max(this.rateLimitState.secondly.resetAtMs, retryAtMs);
    }
    if (this.rateLimitState.rolling) {
      this.rateLimitState.rolling.remaining = 0;
      this.rateLimitState.rolling.resetAtMs = Math.max(this.rateLimitState.rolling.resetAtMs, retryAtMs);
      return;
    }

    this.rateLimitState.rolling = {
      max: 1,
      remaining: 0,
      intervalMs: Math.max(1000, retryAtMs - now),
      resetAtMs: retryAtMs,
    };
  }

  private computeDailyPacingNextAt(resetAtMs: number, dailyMax: number, dailyRemaining: number): number {
    const now = Date.now();
    if (dailyRemaining <= 0) return now;

    const lowWatermark = Math.max(DAILY_MIN_REMAINING_BUFFER, Math.floor(dailyMax * DAILY_LOW_WATERMARK_RATIO));
    if (dailyRemaining > lowWatermark) return 0;

    const msUntilReset = Math.max(0, resetAtMs - now);
    const spreadMs = Math.max(200, Math.floor(msUntilReset / Math.max(dailyRemaining, 1)));
    return now + spreadMs;
  }

  private isDailyQuotaExhausted(now = Date.now()): boolean {
    const daily = this.rateLimitState.daily;
    return Boolean(daily && now < daily.resetAtMs && daily.remaining <= 0);
  }

  private dailyQuotaError(details?: unknown): CliError {
    const daily = this.rateLimitState.daily;
    return new CliError(
      "RATE_LIMIT_DAILY_EXHAUSTED",
      "HubSpot daily API quota appears exhausted for current credentials.",
      429,
      {
        ...(daily ? {
          resetAt: new Date(daily.resetAtMs).toISOString(),
          dailyMax: daily.max,
          dailyRemaining: daily.remaining,
        } : {}),
        ...(details !== undefined ? { details } : {}),
      },
    );
  }
}

function isEnvTrue(value: string | undefined): boolean {
  if (!value) return false;
  const normalized = value.trim().toLowerCase();
  return normalized === "1" || normalized === "true" || normalized === "yes";
}

async function safeJson(response: Response): Promise<unknown> {
  // Read body as text first, then JSON.parse, to avoid "Body is unusable"
  // error when response.json() consumes the stream and fails on non-JSON.
  let text: string;
  try {
    text = await response.text();
  } catch {
    // Fallback if text() is unavailable (shouldn't happen with real fetch)
    try { return await response.json(); } catch { return {}; }
  }
  try {
    return JSON.parse(text);
  } catch {
    return { message: text };
  }
}

function resolveIdempotencyKey(method: string, provided?: string): string | undefined {
  if (!isWriteMethod(method)) return undefined;
  const normalized = provided?.trim();
  if (normalized) return normalized;
  return randomUUID();
}

function isWriteMethod(method: string): boolean {
  return method === "POST" || method === "PATCH" || method === "PUT" || method === "DELETE";
}

function parsePositiveInt(value: string | null): number | undefined {
  if (!value) return undefined;
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed <= 0) return undefined;
  return Math.floor(parsed);
}

function parseNonNegativeInt(value: string | null): number | undefined {
  if (!value) return undefined;
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed < 0) return undefined;
  return Math.floor(parsed);
}

function parseRetryAfterMs(value: string | null): number | undefined {
  if (!value) return undefined;
  const normalized = value.trim();
  if (!normalized) return undefined;
  const seconds = Number(normalized);
  if (Number.isFinite(seconds) && seconds >= 0) return Math.floor(seconds * 1000);
  const dateMs = Date.parse(normalized);
  if (!Number.isFinite(dateMs)) return undefined;
  return Math.max(0, dateMs - Date.now());
}

function isDailyRateLimit(details: unknown): boolean {
  if (!details || typeof details !== "object" || Array.isArray(details)) return false;
  const record = details as Record<string, unknown>;
  const policyName = typeof record.policyName === "string" ? record.policyName.toUpperCase() : "";
  const message = typeof record.message === "string" ? record.message.toLowerCase() : "";
  return policyName === "DAILY" || message.includes("daily limit");
}

function nextUtcMidnightMs(nowMs: number): number {
  const now = new Date(nowMs);
  return Date.UTC(
    now.getUTCFullYear(),
    now.getUTCMonth(),
    now.getUTCDate() + 1,
    0, 0, 0, 0,
  );
}

/**
 * Return the epoch ms of the next midnight in the given IANA timezone.
 * HubSpot resets daily usage at midnight in the portal's own timezone.
 * Falls back to UTC if the timeZone is "UTC" or if Intl formatting fails.
 */
function nextMidnightMs(nowMs: number, timeZone: string): number {
  if (!timeZone || timeZone === "UTC") return nextUtcMidnightMs(nowMs);

  try {
    // Render the current instant as the local date in the target timezone.
    const fmt = new Intl.DateTimeFormat("en-US", {
      timeZone,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hour12: false,
    });
    const parts = Object.fromEntries(fmt.formatToParts(new Date(nowMs)).map(p => [p.type, p.value]));
    const localNow = new Date(`${parts.year}-${parts.month}-${parts.day}T${parts.hour === "24" ? "00" : parts.hour}:${parts.minute}:${parts.second}Z`).getTime();

    // Offset between UTC and local wall time (ms)
    const offsetMs = localNow - nowMs;

    // Compute midnight in local wall time, expressed in UTC-epoch ms
    const localDate = new Date(localNow);
    const localMidnightUtcMs = Date.UTC(
      localDate.getUTCFullYear(),
      localDate.getUTCMonth(),
      localDate.getUTCDate() + 1,
      0, 0, 0, 0,
    );
    // Adjust back from "local wall time expressed as UTC" to actual UTC epoch
    return localMidnightUtcMs - offsetMs;
  } catch {
    return nextUtcMidnightMs(nowMs);
  }
}
